// <auto-generated />
using EasyCargo3D.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyCargo3D.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613011236_InitContainerTypes")]
    partial class InitContainerTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyCargo3D.Models.ContainerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Height")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Length")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<double>("MaxWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<double>("Width")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ContainerTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "20ft",
                            Height = 228.0,
                            Icon = "&#x1F6A2;",
                            IsActive = true,
                            Length = 585.0,
                            MaxWeight = 28200.0,
                            Name = "20ft Standard",
                            SortOrder = 1,
                            Width = 235.0
                        },
                        new
                        {
                            Id = 2,
                            Code = "40ft",
                            Height = 228.0,
                            Icon = "&#x1F6A2;",
                            IsActive = true,
                            Length = 1185.0,
                            MaxWeight = 26750.0,
                            Name = "40ft Standard",
                            SortOrder = 2,
                            Width = 235.0
                        },
                        new
                        {
                            Id = 3,
                            Code = "40hc",
                            Height = 268.0,
                            Icon = "&#x1F4E6;",
                            IsActive = true,
                            Length = 1185.0,
                            MaxWeight = 26460.0,
                            Name = "40ft High Cube",
                            SortOrder = 3,
                            Width = 235.0
                        },
                        new
                        {
                            Id = 4,
                            Code = "45hc",
                            Height = 269.0,
                            Icon = "&#x1F4E6;",
                            IsActive = true,
                            Length = 1351.0,
                            MaxWeight = 27600.0,
                            Name = "45ft High Cube",
                            SortOrder = 4,
                            Width = 235.0
                        },
                        new
                        {
                            Id = 5,
                            Code = "truck",
                            Height = 270.0,
                            Icon = "&#x1F69B;",
                            IsActive = true,
                            Length = 1360.0,
                            MaxWeight = 24000.0,
                            Name = "Truck 13.6m",
                            SortOrder = 5,
                            Width = 240.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
