// <auto-generated />
using System;
using EasyCargo3D.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyCargo3D.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyCargo3D.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EasyCargo3D.Models.ContainerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Height")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Length")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<double>("MaxWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<double>("Width")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ContainerTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "20ft",
                            Height = 228.0,
                            Icon = "&#x1F6A2;",
                            IsActive = true,
                            Length = 585.0,
                            MaxWeight = 28200.0,
                            Name = "20ft Standard",
                            SortOrder = 1,
                            Width = 235.0
                        },
                        new
                        {
                            Id = 2,
                            Code = "40ft",
                            Height = 228.0,
                            Icon = "&#x1F6A2;",
                            IsActive = true,
                            Length = 1185.0,
                            MaxWeight = 26750.0,
                            Name = "40ft Standard",
                            SortOrder = 2,
                            Width = 235.0
                        },
                        new
                        {
                            Id = 3,
                            Code = "40hc",
                            Height = 268.0,
                            Icon = "&#x1F4E6;",
                            IsActive = true,
                            Length = 1185.0,
                            MaxWeight = 26460.0,
                            Name = "40ft High Cube",
                            SortOrder = 3,
                            Width = 235.0
                        },
                        new
                        {
                            Id = 4,
                            Code = "45hc",
                            Height = 269.0,
                            Icon = "&#x1F4E6;",
                            IsActive = true,
                            Length = 1351.0,
                            MaxWeight = 27600.0,
                            Name = "45ft High Cube",
                            SortOrder = 4,
                            Width = 235.0
                        },
                        new
                        {
                            Id = 5,
                            Code = "truck",
                            Height = 270.0,
                            Icon = "&#x1F69B;",
                            IsActive = true,
                            Length = 1360.0,
                            MaxWeight = 24000.0,
                            Name = "Truck 13.6m",
                            SortOrder = 5,
                            Width = 240.0
                        });
                });

            modelBuilder.Entity("EasyCargo3D.Models.PalletType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Height")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Length")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<double>("Width")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PalletTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "euro",
                            Color = "#F39C12",
                            Height = 144.0,
                            IsActive = true,
                            Length = 120.0,
                            Name = "Euro Pallet 120x80",
                            SortOrder = 1,
                            Weight = 500.0,
                            Width = 80.0
                        },
                        new
                        {
                            Id = 2,
                            Code = "amer",
                            Color = "#3498DB",
                            Height = 144.0,
                            IsActive = true,
                            Length = 120.0,
                            Name = "American Pallet 120x100",
                            SortOrder = 2,
                            Weight = 600.0,
                            Width = 100.0
                        },
                        new
                        {
                            Id = 3,
                            Code = "half",
                            Color = "#2ECC71",
                            Height = 100.0,
                            IsActive = true,
                            Length = 60.0,
                            Name = "Half Pallet 60x80",
                            SortOrder = 3,
                            Weight = 250.0,
                            Width = 80.0
                        },
                        new
                        {
                            Id = 4,
                            Code = "ind",
                            Color = "#E74C3C",
                            Height = 150.0,
                            IsActive = true,
                            Length = 120.0,
                            Name = "Industrial 120x120",
                            SortOrder = 4,
                            Weight = 700.0,
                            Width = 120.0
                        },
                        new
                        {
                            Id = 5,
                            Code = "custom",
                            Color = "#9B59B6",
                            Height = 86.0,
                            IsActive = true,
                            Length = 52.0,
                            Name = "Custom Box",
                            SortOrder = 5,
                            Weight = 0.0,
                            Width = 40.0
                        });
                });

            modelBuilder.Entity("EasyCargo3D.Models.PlanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("EasyCargo3D.Models.UserWorkshop", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "WorkshopId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("UserWorkshops");
                });

            modelBuilder.Entity("EasyCargo3D.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("EasyCargo3D.Models.PlanEntity", b =>
                {
                    b.HasOne("EasyCargo3D.Models.AppUser", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EasyCargo3D.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyCargo3D.Models.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("CreatedBy");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("EasyCargo3D.Models.UserWorkshop", b =>
                {
                    b.HasOne("EasyCargo3D.Models.AppUser", "User")
                        .WithMany("UserWorkshops")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyCargo3D.Models.Workshop", "Workshop")
                        .WithMany("UserWorkshops")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("EasyCargo3D.Models.AppUser", b =>
                {
                    b.Navigation("UserWorkshops");
                });

            modelBuilder.Entity("EasyCargo3D.Models.Workshop", b =>
                {
                    b.Navigation("UserWorkshops");
                });
#pragma warning restore 612, 618
        }
    }
}
